### ISSUE TITLE
SDL in-tree build error in Windows

### ISSUE THREAD

**Issue by nonew** [google/flatui#10]
Hello, Sir
I met a build issue when use CMake(version 3.6.2) in Windows, (same result for CMake CMakeLists.txt  command)

D:\work\flatui>cmake -G "Visual Studio 14 2015"
-- FlatUI standalone: building tests and sample
-- FPLBase library: not building samples
CMake Error at dependencies/sdl/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there

-- Configuring incomplete, errors occurred!
See also "D:/work/flatui/CMakeFiles/CMakeOutput.log".

Seems that it is a bug in SDL CMakeLists.txt that prevents SDL from being built out-of-tree if the calling project is being built in-tree.
Here is script in SDL CMakeLists.txt
if(${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR})
  message(FATAL_ERROR "Prevented in-tree built. Please create a build directory outside of the SDL source code and call cmake from there")
endif()

Do you guys know how to fix it?

BR, nonew

**Comment by jsanmiya** [comment]
Hi BR,

That's some excellent debugging. We came to the same conclusion, and opened
a bug with the SDL team.

In the meantime, we hacked around it with this fix:
https://github.com/google/fplbase/blob/master/CMakeLists.txt#L143

It appears that flatui is pinned to an earlier version of fplbase and
doesn't currently have that fix, though. We'll have to push flatui again.
But to get you going, you can patch your fplbase CMakeLists.txt with the
lines above and the modified SDL CMakeLists.txt file
<https://github.com/google/fplbase/blob/develop/cmake/sdl/CMakeLists.txt>
that gets copied over.

All the best,
Jason

**Comment by jsanmiya** [comment]
FlatUI is now referencing a version of FPLBase that has the workaround. Should be fixed now :-)
