### ISSUE TITLE
Compilation problem on Ubuntu

### ISSUE THREAD

**Issue by filippobrizzi** [google/flatui#11]
CMake Error at cmake/freetype/CMakeLists.txt:70 (add_library):
  Cannot find source file:
flatui/dependencies/flatui/src/libpng_to_stbimage/pngshim.cpp

actually pngshim.cpp
is in flatui/src/libpng_to_stbimage/pngshim.cpp
so the CMakeLists.txt should be changed from 
${dependencies_flatui_dir}/src/libpng_to_stbimage/pngshim.cpp
to
${CMAKE_SOURCE_DIR}/src/libpng_to_stbimage/pngshim.cpp

_motive_ doesn't appear in dependencies, despite having cloned with --recursive and cmake fails because it cannot find it.
I have download motive from https://github.com/google/motive and placed in dependencies.

At this point cmake complete successful. 

I had to remove -Werror flag because both motive don't compile.
The first because of the loc 200 and 206 in matrix_processor.cpp
That trigger the warning strict-aliasing.

Compiling sample fails because this command at line 262 of main CMakeLists.txt is wrong:
 COMMAND ${CMAKE_COMMAND} -E copy
          ${dependencies_flatui_dir}/sample/serialization/first_menu.json ${flatui_assets_dir}/serialization
      COMMAND ${CMAKE_COMMAND} -E copy
          ${dependencies_flatui_dir}/sample/serialization/second_menu.json ${flatui_assets_dir}/serialization)

Should be
COMMAND ${CMAKE_COMMAND} -E copy
          ${CMAKE_SOURCE_DIR}/sample/serialization/first_menu.json ${flatui_assets_dir}/serialization
      COMMAND ${CMAKE_COMMAND} -E copy
          ${CMAKE_SOURCE_DIR}/sample/serialization/second_menu.json ${flatui_assets_dir}/serialization)

Once compiled I tryed to run any samples, but nothing is displayed and to kill the application I have to kill it with -9.

Any Ideas of what I am doing wrong?

**Comment by johnb003** [comment]
Thank you for trying to dig past these errors.
There is a problem in our config that's causing flatui to be searched for in the dependencies path of flatui (As you've noticed, it's not supposed to be a dependency of itself). Jason has a fix coming soon.

**Comment by filippobrizzi** [comment]
What about motive missing? and the fact that it fails to compile due to the -Werror flag?

**Comment by johnb003** [comment]
I can't say for certain. I tested on Mac having many of the same issues, and so I'm thinking many of your problems will go away with the proper pathing fix. Motive has been addressed.

The warnings may be specific to the linux build? I was testing on OSX, but I'll make sure Jason is aware, since he's the one patching this up right now.

**Comment by jsanmiya** [comment]
Hi filippobrizzi, thanks for pointing this out. There were a couple of bugs here that are causing the two problems your seeing in the GitHub directory layout. I have fixes for them internally. Will push them tomorrow.

**Comment by jsanmiya** [comment]
Hey filippobrizzi, I've uploaded fixes to flatui and fplutil for the issues with Ubuntu that you found. 

I also noticed that we're missing build instructions for some of the tools that are needed to build flatui under Ubuntu. I've made an internal bug for me to update the build instructions, but in the meanwhile, can you please install the prerequisites for FPLBase? (http://google.github.io/fplbase/fplbase_guide_linux.html)

Please let me know if you're still having troubles, and thanks again for pointing them out.

**Comment by filippobrizzi** [comment]
Wow now everything worked super smooth!
Thank you for the quick fix!
