### ISSUE TITLE
compilation problem on OSX

### ISSUE THREAD

**Issue by AdrianAtGoogle** [google/flatui#12]
following instructions on https://google.github.io/flatui/flatui_guide_osx.html

- ran `git clone --recursive https://github.com/google/flatui.git`
- ran `cd flatui`
- ran `cmake -G Xcode .`

Result:

```
-- FlatUI standalone: building tests and samples
-- FPLBase library: not building samples
CMake Error at dependencies/sdl/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there


-- Configuring incomplete, errors occurred!
See also "/Users/xxxxx/dev/flatui/CMakeFiles/CMakeOutput.log".
```

attempts to follow the instructions re: SDL failure have borne no fruit

**Comment by jsanmiya** [comment]
Hm, thanks for letting us know.

We patched the buggy SDL CMakeLists.txt file in
dependencies/fplbase/cmake/sdl/CMakeLists.txt. This file is supposed to be
copied onto dependencies/sdl/CMakeLists.txt this build code in
dependencies/fplbase/CMakeLists.txt.

    # Fix bug in SDL CMakeLists.txt that prevents SDL from being built
    # out-of-tree if the calling project is being built in-tree.
    # SDL has to be built out-of-tree, but it checks the global variables
    # (e.g. CMAKE_SOURCE_DIR) instead of the current variables
    # (e.g. CMAKE_CURRENT_SOURCE_DIR), so its check is too strict.
    # We hack the SDL CMakeLists.txt file until it is properly fixed
upstream.
    file(COPY cmake/sdl/CMakeLists.txt DESTINATION ${dependencies_sdl_dir})
    set(FORCE_STATIC_VCRT ON CACHE BOOL "")
    add_subdirectory(${dependencies_sdl_dir} ${tmp_dir}/sdl)
    restore_compiler_flags()

Can you please take a look at dependencies/sdl/CMakeLists.txt to see if
it's getting stomped by our patched version?

**Comment by jsanmiya** [comment]
Thanks for pointing out this bug, Adrian.

As you noticed, the fplbase/cmake/sdl/CMakeLists.txt file was accidentally
reverted to an earlier version. This has been fixed in,

https://github.com/google/fplbase/commit/8f95f31f1d8d58e57e945d781df9dd8b6fdbec31

and flatui's submodule has been updated to reference the fix. Should be
good now. :-)

**Comment by AdrianAtGoogle** [comment]
Awesome, thank you!
