### ISSUE TITLE
Android compilation issue - toolchain 4.9?

### ISSUE THREAD

**Issue by Whiteseeker** [google/flatui#6]
I'm using the toolchain 4.9 and have that compilation issue:

dmabin-macbookpro:jni dmabin$ **ndk-build APP_ABI=all**
[arm64-v8a] Install        : libSDL2_empty.so => libs/arm64-v8a/libSDL2_empty.so
install -p /Users/dmabin/Documents/dev/CppIAP/flatui/repo/libs/arm64-v8a/libSDL2_empty.so /Users/dmabin/Documents/dev/CppIAP/flatui/repo/libs/arm64-v8a/libSDL2.so
[arm64-v8a] StaticLibrary  : libSDL2.a
[x86_64] Install        : libSDL2_empty.so => libs/x86_64/libSDL2_empty.so
install -p /Users/dmabin/Documents/dev/CppIAP/flatui/repo/libs/x86_64/libSDL2_empty.so /Users/dmabin/Documents/dev/CppIAP/flatui/repo/libs/x86_64/libSDL2.so
[x86_64] StaticLibrary  : libSDL2.a
[mips64] Compile        : webp <= tree.c
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s: Assembler messages:
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:381: **Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $31,0($17)'**
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:783: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $5,0($24)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:1176: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $4,0($25)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:1469: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $6,0($10)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2130: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $3,0($5)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2202: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $14,0($10)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2272: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $31,0($14)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2343: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $5,0($24)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2601: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $6,0($3)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2673: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $24,0($25)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2744: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $6,0($8)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2817: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $23,0($5)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:2920: Error: opcode not supported on this processor: mips64r6 (mips64r6)`ulw $31,0($23)'
/var/folders/fp/ttp_xh810tsbn342c_9_9btr009c3c/T//cc0797CW.s:3722: Error: opcode not supported on this processor: mips64r6 (mips64r6) `ulw $2,0($24)'
make: **\* [/Users/dmabin/Documents/dev/CppIAP/flatui/repo/obj/local/mips64/objs/webp/src/dec/tree.o] Error 1

**Comment by hak** [comment]
Could you try NDK r12 or newer?
#In those toolchain, Clang is the default compiler and GCC is deprecated.

**Comment by Whiteseeker** [comment]
Obsolete
